# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Self Hosted Agent Pool
  demands:
  - agent.name -equals az-agent-tatupc-api

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(29ab5faf-90a7-4d8c-9f5c-6c83f5d566e9)'
    appType: 'webApp'
    appName: 'mymovieonline'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
